CREATE SCHEMA IF NOT EXISTS PCINFO AUTHORIZATION sa;

CREATE TABLE IF NOT EXISTS CATEGORY(CATEGORY_ID INT auto_increment NOT NULL, NAME VARCHAR(255),URL VARCHAR(255),IS_ACTIVE BOOLEAN);

CREATE TABLE IF NOT EXISTS SUB_CATEGORY(SUB_CATEGORY_ID INT auto_increment NOT NULL, NAME VARCHAR(255),URL VARCHAR(255),URL_KEY VARCHAR(255),CATEGORY_ID INT);

CREATE TABLE IF NOT EXISTS PRODUCT(PRODUCT_ID INT auto_increment NOT NULL, PRODUCT_NAME VARCHAR(255),DESCRIPTION VARCHAR(255),URL VARCHAR(255),CURRENCY VARCHAR(10),CATEGORY_ID INT,SUBCATEGORY_ID INT);


